[package]
name = "dynamic-object"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.dynamic]
path = "./dynamic"

[dependencies.dynamic_derive]
path = "derive"
